export const COMMAND_PREFIX = "$";
export const CHECK_IN_CHANNEL_ID = "932469593543413780";
export const CHECK_IN_USER_ID = "229105932993429504";
export const QUESTIONS = [
  "how are you?",
  "what's the worst FFXIV race/gender combination?",
  "how many heads does a 12-legged horse have?",
  "what is in my pocket?",
  "I always tell the truth, and my brother always lies. Behind us are two doors, one leading to infinite wealth and another leading to a deadly rabbit. You may ask one question.",
  "if it looks like a duck, quacks like a duck, and talks like a duck, is it delicious?",
  "what has two hands and can tell the time?",
  "yesterday was February 28th. What is today?",
  "if you mix yellow and blue paint, what color do you get?",
  "if you start with $1000, and compound daily at 10% APR, how long before you're a millionaire?",
  "who is your favorite Powerpuff Girl?",
  "have you ever heard a giraffe talk?",
  "what weird food combinations do you really enjoy?",
  "what social stigma does society need to get over?",
  "what food have you never eaten but would really like to try?",
  "what's something you really resent paying for?",
  "what would a world populated by clones of you be like?",
  "do you think that aliens exist?",
  "what are you currently worried about?",
  "where are some unusual places you've been?",
  "where do you get your news?",
  "what are some red flags to watch out for in daily life?",
  "what movie can you watch over and over without ever getting tired of?",
  "when you are old, what do you think children will ask you to tell stories about?",
  "if you could switch two movie characters, what switch would lead to the most inappropriate movies?",
  "what inanimate object would be the most annoying if it played loud upbeat music while being used?",
  "when did something start out badly for you but in the end, it was great?",
  "how would your country change if everyone, regardless of age, could vote?",
  "what animal would be cutest if scaled down to the size of a cat?",
  "if your job gave you a surprise three day paid break to rest and recuperate, what would you do with those three days?",
  "what's wrong but sounds right?",
  "what's the most epic way you've seen someone quit or be fired?",
  "if you couldn't be convicted of any one type of crime, what criminal charge would you like to be immune to?",
  "what's something that will always be in fashion, no matter how much time passes?",
  "what actors or actresses play the same character in almost every movie or show they do?",
  "in the past people were buried with the items they would need in the afterlife, what would you want buried with you so you could use it in the afterlife?",
  "what's the best / worst practical joke that you've played on someone or that was played on you?",
  "who do you go out of your way to be nice to?",
  "where do you get most of the decorations for your home?",
  "what food is delicious but a pain to eat?",
  "who was your craziest / most interesting teacher",
  "what “old person” things do you do?",
  "what was the last photo you took?",
  "what is the most amazing slow motion video you've seen?",
  "which celebrity do you think is the most down to earth?",
  "what would be the worst thing to hear as you are going under anesthesia before heart surgery?",
  "what's the spiciest thing you've ever eaten?",
  "what's the most expensive thing you've broken?",
  "what obstacles would be included in the World's most amazing obstacle course?",
  "what makes you roll your eyes every time you hear it?",
  "what do you think you are much better at than you actually are?",
  "should kidneys be able to be bought and sold?",
  "what's the most creative use of emojis you've ever seen?",
  "what riddles do you know?",
  "what's your cure for hiccups?",
  "what invention doesn't get a lot of love, but has greatly improved the world?",
  "what's the most interesting building you've ever seen or been in?",
  "what mythical creature do you wish actually existed?",
  "what are your most important rules when going on a date?",
  "how do you judge a person?",
  "if someone narrated your life, who would you want to be the narrator?",
  "what was the most unsettling film you've seen?",
  "what unethical experiment would have the biggest positive impact on society as a whole?",
  "when was the last time you were snooping, and found something you wish you hadn't?",
  "which celebrity or band has the worst fan base?",
  "what are you interested in that most people aren't?",
  "if you were given a PhD degree, but had no more knowledge of the subject of the degree besides what you have now, what degree would you want to be given to you?",
  "what smartphone feature would you actually be excited for a company to implement?",
  "what's something people don't worry about but really should?",
  "what movie quotes do you use on a regular basis?",
  "do you think that children born today will have better or worse lives than their parents?",
  "what's the funniest joke you know by heart?",
  "when was the last time you felt you had a new lease on life?",
  "what's the funniest actual name you've heard of someone having?",
  "which charity or charitable cause is most deserving of money?",
  "what TV show character would it be the most fun to change places with for a week?",
  "what was cool when you were young but isn't cool now?",
  "if you were moving to another country, but could only pack one carry-on sized bag, what would you pack?",
  "what's the most ironic thing you've seen happen?",
  "if magic was real, what spell would you try to learn first?",
  "if you were a ghost and could possess people, what would you make them do?",
  "what goal do you think humanity is not focused enough on achieving?",
  "what problem are you currently grappling with?",
  "what character in a movie could have been great, but the actor they cast didn't fit the role?",
  "what game have you spent the most hours playing?",
  "what's the most comfortable bed or chair you've ever been in?",
  "what's the craziest conversation you've overheard?",
  "what's the hardest you've ever worked?",
  "what movie, picture, or video always makes you laugh no matter how often you watch it?",
  "what artist or band do you always recommend when someone asks for a music recommendation?",
  "if you could have an all-expenses paid trip to see any famous world monument, which monument would you choose?",
  "if animals could talk, which animal would be the most annoying?",
  "what's the most addicted to a game you've ever been?",
  "what's the coldest you've ever been?",
  "which protagonist from a book or movie would make the worst roommate?",
  "do you eat food that's past its expiration date if it still smells and looks fine?",
  "what's the most ridiculous thing you have bought?",
  "what's the funniest comedy skit you've seen?",
  "what's the most depressing meal you've eaten?",
  "what tips or tricks have you picked up from your job / jobs?",
  "what outdoor activity haven't you tried, but would like to?",
  "what songs hit you with a wave of nostalgia every time you hear them?",
  "what's the worst backhanded compliment you could give someone?",
  "what's the most interesting documentary you've ever watched?",
  "what was the last song you sang along to?",
  "what's the funniest thing you've done or had happen while your mind was wandering?",
  "what app can you not believe someone hasn't made yet?",
  "when was the last time you face palmed?",
  "if you were given five million dollars to open a small museum, what kind of museum would you create?",
  "which of your vices or bad habits would be the hardest to give up?",
  "what really needs to be modernized?",
  "when was the last time you slept more than nine hours?",
  "how comfortable are you speaking in front of large groups of people?",
  "what's your worst example of procrastination?",
  "who has zero filter between their brain and mouth?",
  "what was your most recent lie?",
  "when was the last time you immediately regretted something you said?",
  "what would be the best thing you could reasonably expect to find in a cave?",
  "what did you think was going to be amazing but turned out to be horrible?",
  "what bit of trivia do you know that is very interesting but also very useless?",
  "what's the silliest thing you've seen someone get upset about?",
  "what animal or plant do you think should be renamed?",
  "what was the best thing that happened to you today?",
  "as a child, what did you think would be awesome about being an adult, but isn't as awesome as you thought it would be?",
  "when's censorship warranted?",
  "what's the most boring super hero you can come up with?",
  "what would be some of the downsides of certain superpowers?",
  "what word is a lot of fun to say?",
  "what current trend do you hope will go on for a long time?",
  "what actors or actresses can't play a different character because they played their most famous character too well?",
  "where's your go to restaurant for amazing food?",
  "what's something that all your friends agree on?",
  "what's your best story from a wedding?",
  "what languages do you wish you could speak?",
  "what's the most pleasant sounding accent?",
  "what's something that everyone, absolutely everyone, in the entire world can agree on?",
  "what country is the strangest?",
  "what's the funniest word in the English language?",
  "what's some insider knowledge that only people in your line of work have?",
  "who do you wish you could get back into contact with?",
  "how do you make yourself sleep when you can't seem to get to sleep?",
  "if people receive a purple heart for bravery, what would other color hearts represent?",
  "what are some of the best vacations you've had?",
  "if there was a book of commandments for the modern world, what would some of the rules be?",
  "what's the craziest video you've ever seen?",
  "what's your “Back in my day, we…”?",
  "if you could know the truth behind every conspiracy, but you would instantly die if you hinted that you knew the truth, would you want to know?",
  "what animal would be the most terrifying if it could speak?",
  "what's the worst hairstyle you've ever had?",
  "what habit do you have now that you wish you started much earlier?",
  "if you were given one thousand acres of land that you didn't need to pay taxes on but couldn't sell, what would you do with it?",
  "what about the opposite sex confuses you the most?",
  "when was the last time you yelled at someone?",
  "what's the opposite of a koala?",
  "what kinds of things do you like to cook or are good at cooking?",
  "what life skills are rarely taught but extremely useful?",
  "what movie universe would be the worst to live out your life in?",
  "if you could hack into any one computer, which computer would you choose?",
  "who do you feel like you know even though you've never met them?",
  "what's the most ridiculous animal on the planet?",
  "what's the worst thing you've eaten out of politeness?",
  "what's the most historic thing that has happened in your lifetime?",
  "what happens in your country regularly that people in most countries would find strange or bizarre?",
  "what has been blown way out of proportion?",
  "when was a time you acted nonchalant but were going crazy inside?",
  "what's about to get much better?",
  "what are some clever examples of misdirection you've seen?",
  "what's your funniest story involving a car?",
  "what would be the click-bait titles of some popular movies?",
  "if you built a themed hotel, what would the theme be and what would the rooms look like?",
  "what scientific discovery would change the course of humanity overnight if it was discovered?",
  "do you think that humans will ever be able to live together in harmony?",
  "what would your perfect bar look like?",
  "what's the scariest non-horror movie?",
  "what's the most amazing true story you've heard?",
  "what's the grossest food that you just can't get enough of?",
  "what brand are you most loyal to?",
  "what's the most awkward thing that happens to you on a regular basis?",
  "if you had to disappear and start a whole new life, what would you want your new life to look like?",
  "what movie or book do you know the most quotes from?",
  "what was one of the most interesting concerts you've been to?",
  "where are you not welcome anymore?",
  "what do you think could be done to improve the media?",
  "what's the most recent show you've binge watched?",
  "what's the worst movie trope?",
  "what's a common experience for many people that you've never experienced?",
  "what are some misconceptions about your hobby?",
  "what's the smartest thing you've seen an animal do?",
  "what's the most annoying noise?",
  "what's your haunted house story?",
  "what did you Google last?",
  "what's the dumbest thing someone has argued with you about?",
  "if money and practicality weren't a problem, what would be the most interesting way to get around town?",
  "what's the longest rabbit hole you've been down?",
  "what's the saddest scene in a movie or TV series?",
  "what's the most frustrating product you own?",
  "what inconsequential super power would you like to have?",
  "what qualities do all your friends have in common?",
  "what odd smell do you really enjoy?",
  "what's the coolest animal you've seen in the wild?",
  "what's the best lesson you've learned from a work of fiction?",
  "what food do you crave most often?",
  "who in your life has the best / worst luck?",
  "what fashion trend makes you cringe or laugh every time you see it?",
  "what's your best story of you or someone else trying to be sneaky and failing miserably?",
  "which apocalyptic dystopia do you think is most likely?",
  "if you had a HUD that showed three stats about any person you looked at, what three stats would you want it to show?",
  "what's the funniest thing you've seen a kid do?",
  "what's your secret talent?",
  "what's the best way you or someone you know has gotten out of a ticket / trouble with the law?",
  "tear gas makes people cry and laughing gas makes people giggle, what other kinds of gases do you wish existed?",
  "what's the most beautiful beach you've been to?",
  "what's the most anxiety inducing thing you do on a regular basis?",
  "what's something that everyone agrees we should change, but somehow it never changes?",
  "what trend are you tired of?",
  "what's incredibly cheap and you would pay way more for?",
  "what's your grossest bug story?",
  "what would the adult version of an ice-cream truck sell and what song would it play?",
  "what company do you despise?",
  "when was the most inappropriate time you busted out in laughter?",
  "what would be an accurate tag line for each month?",
  "what's the most overrated product out on the market?",
  "what word do you always misspell?",
  "what naps are the most satisfying?",
  "what's the weirdest thing you've found lying on the ground / side of the road?",
  "what's the funniest TV show you've ever seen?",
  "what's the most embarrassing story from your childhood?",
  "what animal is the most majestic?",
  "what's something that everyone knows is true, but we don't like to admit it?",
  "what's the weirdest text or email you've gotten?",
  "what always cheers you up when you think about it?",
  "what sport could you play the longest in a televised game, without anyone discovering you aren't a professional athlete?",
  "if you could talk to animals and they would understand you, but you couldn't understand them, what would you do with that power?",
  "what's the most boring sport, and what would you do to make it more exciting?",
  "what's the creepiest tech out there?",
  "who did you use to look up to, but they screwed up and you lost faith in them?",
  "what's fine in small numbers but terrifying in large numbers?",
  "do you like things to be carefully planned or do you prefer to just go with the flow?",
  "what animal would you most like to eat?",
  "what fictional characters have you had a crush on over the years?",
  "what would the box with all your hopes and dreams inside look like?",
  "what was the worst shopping experience you've ever had?",
  "what story you've heard has stayed with you and always disturbs you every time you think about it?",
  "what was the most important appointment or deadline you missed?",
  "if you were a clown themed super hero, what powers would you have?",
  "if you could airdrop anything you want, worth two million dollars or less, anywhere you want, what would you airdrop and where would you airdrop it?",
  "if you lived in a virtual reality world of your own creation, what would it look like?",
  "what escalated very quickly?",
  "what two things are terrible when separate but great when you put them together?",
  "what did you believe for way too long as a child?",
  "what big event do you think will happen soon that most people aren't expecting?",
  "what still makes you cringe when you think back on it?",
  "what current trend makes no sense to you?",
  "if you owned a restaurant, what kind of food would it serve?",
  "which celebrity is the most likely to have a collection of canes that are just for show?",
  "what's the weirdest crush you've had?",
  "what do a lot of people have very strong opinions about, even though they know very little about it?",
  "what's your go to casino game?",
  "an epic feast is held in your honor, what's on the table?",
  "what's your favorite holiday movie?",
  "who is the most manipulative person you've ever met?",
  "who is the most creative person you know?",
  "what's the funniest pick up line you've heard?",
  "what seemingly innocent question makes you think “It's a trap!”?",
  "how ambitious are you?",
  "what did you like / dislike about where you grew up?",
  "what elements of pop culture will be forever tied in your mind to your childhood?",
  "what's your good luck charm?",
  "what's legal now, but probably won't be in 25 years?",
  "would you want the ability to hear the thoughts of people near you if you couldn't turn the ability off?",
  "when was the last time you stayed up through the entire night?",
  "what's something that people think makes them look cool, but actually has the opposite effect?",
  "what's the oldest thing you own?",
  "what has someone borrowed but never given back?",
  "where is the best place you've been for taking walks?",
  "if cartoon physics suddenly replaced real physics, what are some things you would want to try?",
  "what from the present will withstand the test of time?",
  "who in your life is the worst at using technology?",
  "what's the weirdest conversation you've eavesdropped on?",
  "what just around the corner tech are you eager to get your hands on?",
  "what was the darkest movie you've ever seen?",
  "what do you do when you hear something fall in the middle of the night while you are in bed?",
  "what outfit could you put together from clothes you own to get the most laughs?",
  "what's the most disgusting sounding word in the English language?",
  "what was ruined because it became popular?",
  "what outdated slang do you use on a regular basis?",
  "what was the biggest realization you had about yourself?",
  "what's your best example of easy come, easy go?",
  "what small change greatly improves a person's appearance?",
  "what topic could you spend hours talking about?",
  "what happens regularly that would horrify a person from 100 years ago?",
  "what do a lot of people hope will happen but is just not going to happen?",
  "what's the weirdest thing that has happened to you while working at your job?",
  "what questions would you like to ask a time traveler from 200 years in the future?",
  "which way should toilet paper hang, over or under?",
  "what's the most physically painful thing you've ever experienced?",
  "what horror story do you have from a job you've had?",
  "what's the most rage inducing game you've ever played?",
  "what's the biggest overreaction you've ever seen?",
  "what are some of the most common misconceptions?",
  "what job doesn't exist now but will exist in the future?",
  "what awful movie do you love?",
  "what normally delicious food gets ruined when you wrap it in a tortilla?",
  "what's your best example of fake it till you make it?",
  "what were you completely certain of until you found out you were wrong?",
  "what's something commonly done that gets progressively weirder the more you think about it?",
  "if you were given unlimited resources, how would you lure the worst of humanity into one stadium at the same time?",
  "what do you think about when you hear the word “classy”?",
  "what near future predictions do you have?",
  "what do you need help with most often?",
  "what piece of “art” would you create if you had to pretend to be an artist and submit something to a gallery?",
  "what do you do to make the world a better place?",
  "what's the best and worst thing about the country you are from?",
  "if you were in charge renaming things so that their names would be more accurate, what names would you come up with?",
  "what's better broken than whole?",
  "what values are most important to you?",
  "what's the best sandwich you've ever had?",
  "what's the worst thing you ate from a fast food restaurant?",
  "what's something that I don't know?",
  "what profession doesn't get enough credit or respect?",
  "what memory of yours feels real but is most likely false?",
  "what's your “and then it got worse” story?",
  "what was the most amazing physical feat you've managed to pull off?",
  "what's the most annoying thing about the social media platform you use most often?",
  "if you were hired to show tourists what life is really like where you live, what would you show them / have them do?",
  "what would be the most unsettling thing to keep occasionally finding around your house?",
  "what nicknames do you have for people in your life?",
  "what does the opposite sex do that you wish that you could do, but it's not anatomically feasible or it's socially frowned upon?",
  "how much do you plan / prepare for the future?",
  "what do you hate most and love most about your car?",
  "what weird potato chip flavor that doesn't exist would you like to try?",
  "what's the silliest thing you've convinced someone of?",
  "how much do you think names affect the outcomes of people's lives?",
  "what product or service is way more expensive than it needs to be?",
  "what's the shadiest thing you've seen someone do?",
  "what was the last situation where some weird stuff went down and everyone acted like it was normal, and you weren't sure if you were crazy or everyone around you was crazy?",
  "what did you eat so much of that now you hate it?",
  "what are some of the dumbest lyrics you've heard in a song?",
  "where's the line between soup and cereal?",
  "what word do you always mispronounce?",
  "what do you think you do better than 90% of people?",
  "what would be the worst food to be liquefied and drunk through a straw?",
  "what's the weirdest thing about modern life that people just accept as normal?",
  "how much of your body would you cybernetically enhance if you could?",
  "if you wanted to slowly drive a roommate insane using only notes, what kind of notes would you leave around the house?",
  "if you had a giraffe that you needed to hide, where would you hide it?",
  "what's the clumsiest thing you've done?",
  "what songs do you only know the chorus to?",
  "think of a brand, now what would an honest slogan for that brand be?",
  "what's something common from your childhood that will seem strange to future generations?",
  "what's the most amazing place in nature you've been?",
  "what's quickly becoming obsolete?",
  "where is the most uncomfortable place you have ever slept?",
  "what's the most annoying animal you've encountered?",
  "what's your best example of correlation not equaling causation?",
  "in what situations, do you wish you could throw down a smoke bomb and disappear?",
  "when was the last time you were hopelessly lost?",
  "what songs do you feel compelled to sing along with when you hear them, even if you don't totally know all the words?",
  "what product do you wish a company would make a “smart” version of?",
  "what two films would you like to combine into one?",
  "what's are some of your Pavlovian responses?",
];
